### ISSUE TITLE
Avalonia 0.10 incompatibility

### ISSUE THREAD

**Issue by caunt** [NetSparkleUpdater/NetSparkle#122]
Method not found: 'Void Avalonia.Controls.Image.set_Source(Avalonia.Media.Imaging.IBitmap)'.
   at NetSparkleUpdater.UI.Avalonia.CheckingForUpdatesWindow..ctor(IBitmap iconBitmap)
   at NetSparkleUpdater.UI.Avalonia.UIFactory.ShowCheckingForUpdates()
   at NetSparkleUpdater.SparkleUpdater.<CheckForUpdatesAtUserRequest>d__136.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
   at Test2.Program.Main.d__2.MoveNext() in C:\Users\caunt\Desktop\Kaboom\Test2\Program.cs:line 38

**Comment by Deadpikle** [comment]
Hi @caunt!

Thanks for the report. Right now, since Avalonia 0.10 is just in preview, the "official" NetSparkle compatibility will stick with 0.9 for the time being. However, you should be able to supply your own `UIFactory` and/or GUI items as needed to fix this error without needing an official build.

I'm _quite_ busy this weekend (and in general right now), so until I can take a look at it and supply a workaround to you, the above is what you'll have to rely on. Please be patient with me while I'm busy 😅 Thanks!

**Comment by caunt** [comment]
Hi. Thank you very much for the prompt reply.

I am already working on way that you mentioned 🙂

**Comment by Deadpikle** [comment]
As a side note for future seekers: NetSparkleUpdater 2.0 with the Avalonia UI is now compatible with Avalonia 0.10.
