### ISSUE TITLE
Out of memory issue when RetrieveDestinationFileNameAsync in WebClientFileDownloader is being executed

### ISSUE THREAD

**Issue by avivf88** [NetSparkleUpdater/NetSparkle#342]
Hi,
I have an issue that when the download start sometimes I'm getting an error.
I've debugged it and saw that an exception is being thrown in RetrieveDestinationFileNameAsync method (in WebClientFileDownloader that is implementing the IUpdateDownloader).

I've checked it out and saw that the following command is throwning an "Out of memory exception"

"
using (var response =
                    await httpClient.SendAsync(new HttpRequestMessage
                    {
                        Method = HttpMethod.Head,
                        RequestUri = new Uri(item.DownloadLink)
                    }).ConfigureAwait(false))
"

The reason for the exception is that my download file is pretty big (around 600MB) and this request is allocating the memory despite the method being "Head"

In order to solve that i've added the flag "**HttpCompletionOption.ResponseHeadersRead**" to make sure this request is not allocating memory that is not necessary and it worked.
In addition i saw that you guys are using the same flag in other request in StartFileDownloadAsync method in same class file (WebClientFileDownloader)

**Please let me know what you guys think and if you guys can add this fix on your side**? as i prefer to continue using your IUpdateDownloader implementation instead of overriding it just for this specific fix.

I'm adding here the stack trace of the exception:

   at System.IO.MemoryStream..ctor(Int32 capacity)
   at System.Net.Http.HttpContent.LimitMemoryStream..ctor(Int32 maxSize, Int32 capacity)
   at System.Net.Http.HttpContent.CreateMemoryStream(Int64 maxBufferSize, Exception& error)
   at System.Net.Http.HttpContent.LoadIntoBufferAsync(Int64 maxBufferSize)
   at System.Net.Http.HttpClient.StartContentBuffering(HttpRequestMessage request, CancellationTokenSource cancellationTokenSource, TaskCompletionSource`1 tcs, HttpResponseMessage response)
   at System.Net.Http.HttpClient.<>c__DisplayClass55_0.<SendAsync>b__0(Task`1 task)
--- End of stack trace from previous location ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at SDKServices.NetSparkleAutoUpdateWrapper.<RetrieveDestinationFileNameAsync>d__45.MoveNext()

Thanks in advance,
Aviv

**Comment by Deadpikle** [comment]
@avivf88,

I don't have a problem with that change. Do you want to submit a PR for it? Otherwise, I can make the change.

Thanks so much for reporting!

**Comment by Deadpikle** [comment]
Fixed in 2.1.2. Thanks again!

**Comment by avivf88** [comment]
Thank you for the quick response!
